config/routes.rb
Rails.application.routes.draw do
  resources :cards

  resources :themes

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}", as: "#{action}"
  end 

  root 'pages#home'

end

app/models/card.rb
class Card < ActiveRecord::Base

	belongs_to :theme
	has_many :themes

	mount_uploader :image, ImageUploader # Tells rails to use this uploader for this model.

end

app/models/theme.rb
class Theme < ActiveRecord::Base

	has_many :cards

	mount_uploader :image, ImageUploader # Tells rails to use this uploader for this model.


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    # @title = @theme[card.title.id]
    respond_to do |format|
      if @card.save
        format.html { redirect_to themes_url, :notice => 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:image, :caption, :title, :theme)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def home
		render
	end 

	def about
		render
	end 

	def tips
		render
	end 

  def index
    @cards = Card.all
  end

    def card_params
      params.require(:card).permit(:image, :caption, :title, :theme)
    end
    
end 

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
   end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)
 
    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:title, :image, :description, :caption, :card)
    end
    def card_params
      params.require(:card).permit(:image, :caption, :title, :theme)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/cards/_form.html.erb
<div>
<div class="container bgGrey col-md-12 editpage">

  <div class="col-md-3 newCard">
      <h1> &nbsp &nbsp <center> <strong>Edit card </strong></center></h1>

    <%= bootstrap_form_for(@card) do |f| %>
      <% if @card.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

          <ul>
          <% @card.errors.full_messages.each do |message| %>
             <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="innerCard">

      <div class="field">
        <%= f.select :title, Theme.all.map { |t| t.title}, include_blank:true, label: "Theme" %>
      </div>
      
      <div class="field">
        <%= f.file_field :image %>
      </div>
      <div class="field">
        <%= f.text_field :caption %>
      </div><br>
      <div class="actions">
        <center><%= f.submit "+", :class => " btn btn-info col-md-12 ", :style => "font-size:1.4em;" %></center>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

 

app/views/cards/edit.html.erb
 
<%= render 'form' %>

app/views/cards/index.html.erb
<div class="bgGrey"> 
  <div class="container cardh1">
    <h1> All the Cards</h1> <br>
      <div class="masonry" style="margin-bottom:5em;">

        <% @cards.each do |card| %>
          <div class="boo item card">

            <div>
              <div><%= link_to image_tag(card.image_url, :class => "thumb"), card_path(card.id) %>
              </div>
            </div>


            <div class="edit col-md-12">
              <div class="col-md-10 cap"><strong> <%= card.caption %></strong>
              </div>
                <div class="awesome col-md-2"> 
                  <li><%= link_to content_tag(:i,nil, :class=>"fa fa-cog"), edit_card_path(card) %> </li>
                  <li><%= link_to content_tag(:i,nil, :class=>"fa fa-trash-o"), card, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </li>
                </div>
            </div>
          </div>
        <% end %>
      <div class="card boo item"> 
        <div> <%= link_to content_tag(:i,nil, :class=>"fa fa-plus-square plus"), new_card_path, :class => "btnCard btn btn-sm btn-info col-md-12" %>
        </div>
        <div class="col-md-12 addcard"><h3> add a card</h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<center><span style="font-size:5em; text-align:center; color:#3498DB; opacity:.7;" class="glyphicon glyphicon-cloud"></span></center>

<%= render 'form' %>

app/views/cards/show.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->

 	<li><%= image_tag(@card.image_url, :class => "col-md-5" ) %></li>
 	<br>

  	<h2> <%= @card.caption %> <h2>


<div class="bottomBtn col-md-12">
	<li> <%= link_to 'Edit', edit_card_path(@card), :class => "btn btn-info" %></li> 
	<li> <%= link_to 'Back', cards_path, :class => "btn btn-info" %> </li> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Iris</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>


	<body>
		<%= nav_bar :brand => "The Iris Project", :brand_link => root_path,  :static => :top, :responsive => true do%> 
			<%= menu_group do %> 
				<%= menu_item "Home", root_path %> 
				<%= menu_item "Decks", themes_path %>
				<%= menu_item "Cards", cards_path %>
				<%= menu_item "Tips", tips_path %>
				<%= menu_item "About", about_path %>
			<% end %>
		<% end %>
				

 



	<%= yield %>

	<div class="footer col-md-12 container">
		<div class="foot">
			<div>An Untamed<br>Killer Whale Production</div>
		</div>
	</div>


 	</body>
</html>

app/views/pages/about.html.erb
<div class="cloud3"> </div>
<div class="about"> 
		<div class="aboutsect1">
			<div>
				<h1>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp About</h1>
				<p> &nbsp &nbsp &nbsp &nbsp &nbsp <span style="font-size:1.4em;">An online app</span> crafted  to be a study aid. I was learning different species of flowers and birds and thought, "I wish had this simple app for decades." And now, here it is.  
				<br><br> &nbsp &nbsp &nbsp &nbsp &nbsp Enjoy and learn.
				</p> 
			</div>
		</div>

		<div class="aboutsect1 aboutsect2">
			<div>
				<h1>The Futura</h1>
				<p> &nbsp &nbsp &nbsp &nbsp &nbsp <span style="font-size:1.4em;">Upcoming improvements</span> will be adding personal options and accounts, and to reverse the ability of the cards to show text first then image. 
				<br><br> &nbsp &nbsp &nbsp &nbsp &nbsp 
				Don't hold your breath. 
				</p> 
			</div>
		</div>

				<div class="aboutsect1 aboutsect2 white1">
			<div class="icon col-md-12">
  				<a href="https://github.com/vandoan"><i class="fa fa-github"></i></a>
  				<i style="line-height:2em;" class="fa fa-cloud"></i>
				<a href="mailto:spoonbbill@gmail.com"><i class="fa fa-paper-plane"></i></a>
 			</div>
		</div>

</div>

app/views/pages/home.html.erb
	<div class="welSect1">
	 	<header id="basement" class="band" data-0="background-position:0px 0px;" data-500="background-position:0px -250px;">       
	        <div class="container">
	            <div class="columns sixteen" data-0="opacity: 1" data-180="opacity: 0" data-500="background-position:0px -250px;">          
	            </div>
	        </div>
        	<div class="welTitle"> 
          	  <p>Iris</p>
      		  </div>
	    </header>
	</div>
   
    <div class="welSect2">

 
         <div class="sect2inner">


            <center><p class="welP1 col-md-12">a visual learning aid </p></center> 
            <p class="col-md-5 welP2"><strong>In ancient Greek mythology,<br> Iris, the goddess of the rainbow and the messenger of the gods, travels with the speed of the wind to all corners of the world to deliver their messages.</strong></p>  
        </div> 
    </div>    

    <div class="welSect20">
        <div class="sect20inner">
           
      <div class=" minCard">
        <% @cards = Card.order('created_at DESC').limit(9) %>
        <% @cards.each  do |card| %>
          <div class=" item card" style="width:8%; margin: 1.2%">

            <div>
              <div><%= link_to image_tag(card.image_url, :class => "thumb"), card_path(card.id) %>
              </div>
            </div>
            <div class="edit mincap col-md-12">
              <div class="col-md-10 mincap"><strong> <%= card.caption %></strong>
              </div>

            </div>
          </div>
        <% end %>
      </div>            
    </div> 


    </div>    



    <div class="welSect21">
        <div class="sect2inner">
            <p class="col-md-8 welP4"><strong>number of cards sent online<span class="dreamers">0237</span> </strong></p>  
            
            <p class="col-md-6 welP3"><strong>number of ideas shared <span class="dreams">0129734</span>
            </strong></p>  
            
            <p class="col-md-9 welP5"><strong>number of lives changed <span class="dream">031248</span> </strong></p>  
        </div> 
    </div>    

    <div class="welSect3"> 
         <div class="container col-md-12 sect3inner">
            <p class="wel3P1"><strong>How to use</strong></p>
             
            <p class="wel3P2 col-md-4"><span class="join">001</span> <br><strong> Create a deck | add cards with short messages.</strong></p>  
            
            <p class=" wel3P3"><span class="start">002<br></span><strong> Pick a deck. </strong></p>  

            <p class="col-md-5 wel3P5"><span class="repeat">003</span><strong><br>Learn.  </strong></p>  
        </div>
    </div>


    <div class="welSect4"> 
         <div class="container col-md-12 sect4inner">
            <p class="wel4P1"><strong>IDEAS</strong></p>
             
            <p class="wel4P2 col-md-4"><span class="idea">Geography</span> <br><strong> Names of geographic features, countries, international cities...</strong></p>  
            
            <p class=" wel4P3"><span class="idea">Birds<br></span><strong> Heron, spoonbill,<br> bird of paradise... </strong></p>  

            <p class="col-md-5 wel3P5"><span class="idea">Greek Gods </span><strong><br>Iris, Demeter, Ares, Poseidon, Athena, Apollo...  </strong></p>  
        </div>
    </div>

   <div class="welSect5"> 
        <div class="cloud"> 
        </div>
         <div class="container col-md-12">
            <p class="wel5P1"><strong> - "Learn all the things!"</strong></p>
        </div>
    </div>

    <script type="text/javascript" src="assets/skrollr.min.js"></script>
    <script type="text/javascript">
             skrollr.init();
        </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

app/views/pages/tips.html.erb
<div class="cloud2"> 
        </div><div class="about"> 
 
		<div class="aboutsect1">
			<div>
				<h1>&nbsp &nbsp &nbsp Tips</h1>
				<p> &nbsp &nbsp &nbsp &nbsp &nbsp <span style="font-size:1.4em;">Some words to help you</span> learn and memorize ideas, images, and words. 
				</p> 
			</div>
		</div>

		<div class="aboutsect1 aboutsect2" >
			<div>
				<h1 style="margin-top:4em;">&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp Quantity x Quality </h1>
				<p> &nbsp &nbsp &nbsp &nbsp &nbsp <span style="font-size:1.4em;">Like with most things,</span> to get better at them, you'll need to put in the time. But not only that, you have to be effective. Make sure to be well rested and have little or no distractions. Turn that TV off. The music, too! Your brain can only take in one thing at a time, scientifically proven. Multitasking will just slow you down, so focus and be disciplined.  
				<br><br> &nbsp &nbsp &nbsp &nbsp &nbsp You can do it!

				</p> 
			</div>
		</div>

		<div class="aboutsect1 aboutsect2">
			<div>
				<h1> &nbsp&nbsp &nbsp &nbsp Memorizing</h1>
				<p> &nbsp &nbsp &nbsp &nbsp &nbsp <span style="font-size:1.4em;">Focus</span> on your weaknesses, not on your strength. Review what you already know once in a while, but focus most of your time  on what's hard. With time, you'll get it, and it'll become easier, so be efficient and effective with your time and build on your weaknesses, not strengths. 
				</p> 
			</div>
		</div>


		<div class="aboutsect1 aboutsect2">
			<div>
				<h1>&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp &nbsp Mnemonic</h1>
				<p> &nbsp &nbsp &nbsp &nbsp &nbsp <span style="font-size:1.4em;">Use them!</span> It's the use of letters, ideas or association to help you remember. Connect ideas to visuals. For example, if you have an image of a  petunia flower, try to connect that with a person with the same name. 
				<br><br> &nbsp &nbsp &nbsp &nbsp &nbsp 
	 			You got this. 
	 			</p> 
			</div>
		</div>

		<div class="aboutsect1 aboutsect2">
			<div>
				<h1>&nbsp &nbsp &nbsp&nbsp &nbsp &nbsp Grit</h1>
				<p> &nbsp &nbsp &nbsp &nbsp &nbsp <span style="font-size:1.4em;">Don't give up.</span> Perfect practice makes perfect. The more you learn, the easier it'll get, but if you don't know as much, then life is going to be a lot harder. 
				<br><br> &nbsp &nbsp &nbsp &nbsp &nbsp 
				With anything, it takes practice, time, and discipline. Push yourself and after a while, learning about the world is pretty fun. You just have to get over the hump, but it takes a bit of hard work at first. Just remember, in the end, it's worth it! 
				</p> 
			</div>
		</div>


</div>

app/views/themes/_form.html.erb
<div class="container col-md-12 editpage bgGrey">
  <div class="col-md-3 newCard">
      <h1> &nbsp &nbsp <center><strong>Edit deck </strong></h1></center>

     <%= bootstrap_form_for(@theme) do |f| %>
        <% if @theme.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

            <ul>
            <% @theme.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="innerCard">
          <%= f.text_field :title, :label => "Theme" %>
          <%= f.file_field :image %>
          <%= f.text_area :description, :rows => "4" %>
              <center><%= f.submit "+", :class => " btn btn-info col-md-12 ", :style => "font-size:1.4em;" %></center>
        </div>
      <% end %>
  </div>
</div>

app/views/themes/edit.html.erb
<%= render 'form' %>

app/views/themes/index.html.erb
<div class="bgGrey" style="padding: 0 15%;"> 



    <div class="cardh1 container">
      <h1>Decks</h1>
      <div class="masonry" style="margin-bottom:5em;">

      <% @themes.each do |theme| %>
        <div>
          <div class="boo item card">
            
            <div>
              <div><%= link_to image_tag(theme.image_url, :class => "thumb"), theme_path(theme.id) %> 
              </div> 
            </div>

            <div class="themedivs">
              <br>
              <div class="col-md-10 deckTitle"><h4><%= theme.title %></h4>
                <br>
                <p><%= theme.description %></p>
              </div>

              <div class="awesome col-md-1"> 
                <li><%= link_to content_tag(:i,nil, :class=>"fa fa-cog"), edit_theme_path(theme) %> 
                </li>
                <li><%= link_to content_tag(:i,nil, :class=>"fa fa-trash-o"), theme, method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
              </div>
            </div>

          </div>
        </div>
      <% end %>
        <div>
          <div class="card boo item"> 
            <div> <%= link_to content_tag(:i,nil, :class=>"fa fa-plus-square plus"), new_theme_path, :class => "btnCard btn btn-sm btn-info col-md-12" %>
            </div>
            <div class="col-md-12 addDeck"><h3> add a deck</h3>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/themes/new.html.erb
 
<center><span style="font-size:5em; text-align:center; color:#3498DB;" class="glyphicon glyphicon-plus"></span></center>


<%= render 'form' %>

 

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>


<div class="bgGrey"> 
  <div class="container cardh1">
  <h1>Deck: <%= @theme.title %></h1><br>
    <h3> &nbsp &nbsp <%= @theme.description %> </h3> <br><br>
  <br>
    <div class="masonry" style="margin-bottom:5em;">

        <% @cards = Card.all %>
          <% @cards.each do |card| %>
            <div class="boo item card">

               <% if card.title == @theme.title %>  

                  <div>
                    <div><%= link_to image_tag(card.image_url, :class => "thumb"), card_path(card.id) %>
                    </div>
                  </div>

                  <div class="edit col-md-12">
                    <div class="col-md-10 cap"><strong> <%= card.caption %></strong>
                    </div>
                    <div class="awesome col-md-2"> 
                        <li><%= link_to content_tag(:i,nil, :class=>"fa fa-cog"), edit_card_path(card) %> </li>
                        <li><%= link_to content_tag(:i,nil, :class=>"fa fa-trash-o"), card, method: :delete, data: { confirm: 'Are you sure?' } %>
                        </li>
                    </div>
                  </div>

              <% end %>
            </div>

          <% end %> 

        <%= bootstrap_form_for Card.new do |f| %>
          <div class="innerCard col-md-12 topicCard card">
            <div class="col-md-12" style="margin: 3em 0 0 0;"><center>
              <%= f.hidden_field :title,  value: "#{@theme.title}"  %>
                <%= f.file_field :image %>
                <%= f.text_field :caption, :class => "col-md-12" %>
                <br>
                  <div class="actions">
                  <%= f.submit "+", :class => " btn btn-info col-md-12", :style => "font-size:2.4em; margin:1em 0;" %></center>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
          <div class="col-md-12" style="clear:both; margin:2em;">
            <div> <%= button_to 'Back', themes_path, :style =>"color:white;", :class => "btn btn" %>
            </div>
          </div>
    </div>